services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - nextcloud-network

  nextcloud:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8082:80
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      AWS_CREDENTIALS: ${AWS_CREDENTIALS}
      AWS_SECRET: ${AWS_SECRET}
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER:-admin}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD:-admin}
      NEXTCLOUD_TRUSTED_DOMAINS: localhost:8082
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - db
      - localstack
    networks:
      - nextcloud-network

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    restart: always
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=${AWS_CREDENTIALS}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET}
    volumes:
      - ./localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nextcloud-network

volumes:
  db_data:
    name: nextcloud_localstack_db
  nextcloud_data:
    name: nextcloud_localstack_data

networks:
  nextcloud-network:
    driver: bridge
